org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=*.google.com|*.gradle.org|*.maven.org|repo1.maven.org|dl.google.com|services.gradle.org|plugins.gradle.org|maven.google.com -Dhttps.nonProxyHosts=*.google.com|*.gradle.org|*.maven.org|repo1.maven.org|dl.google.com|services.gradle.org|plugins.gradle.org|maven.google.com
android.useAndroidX=true
android.enableJetifier=true

# Bypass proxy for build repositories
systemProp.http.nonProxyHosts=*.google.com|*.gradle.org|*.maven.org|repo1.maven.org|dl.google.com|services.gradle.org|plugins.gradle.org|maven.google.com
systemProp.https.nonProxyHosts=*.google.com|*.gradle.org|*.maven.org|repo1.maven.org|dl.google.com|services.gradle.org|plugins.gradle.org|maven.google.com
